# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:
    name: MoE Kenya Web Dash Build
    runs-on: node

    strategy:
      matrix:
        node-version: [20.0.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # - name: Adding to Known Hosts
      #   run: |
      #     ssh-keygen -R "[domain.com]:22" || true
      #     ssh-keyscan  -T 100 -t rsa -4  domain.com >> ~/.ssh/known_hosts || true

      - name: Install Packages
        run: npm i --force

      - name: Build
        run: npm run build-prod

      # - name: Deploy to RequestAfrica
      #   run: rsync -av -e ssh  -r dist/*  user@domain.com:/usr/www/html/dash
